class AIService:
    def analyze_team(self, team):
        conference = team.get("conference", "NFL")
        division = team.get("division", "")

        return {
            "summary": (
                f"{team['name']} competes in the {conference} {division}. "
                "This analysis is generated by Between The Huddles AI using team information."
            ),
            "offense": (
                "The offense will succeed by protecting the quarterback, "
                "establishing the run, and limiting turnovers."
            ),
            "defense": (
                "The defense's focus is creating pressure, forcing mistakes, "
                "and limiting explosive plays."
            ),
            "prediction": (
                "This matchup is competitive. Execution in the fourth quarter "
                "and turnover margin will likely decide the outcome."
            )
        }
